# Generated by Django 2.2.12 on 2020-06-04 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, unpack_ipv4=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('mod_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date changed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.UserIP')),
            ],
        ),
    ]
