# Generated by Django 2.2.12 on 2020-06-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_add_userip_and_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='mode',
            field=models.TextField(default='acc.act', max_length=10),
        ),
    ]
