# Generated by Django 3.1.1 on 2021-05-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_add_activationcode_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='email',
            field=models.TextField(default='', max_length=100),
        ),
    ]
