#! /bin/sh

echo "postinstall XC"

XC_HOME=/var/lib/ai-and-it/xc

python3 -m pip install Django==3.1.1

$XC_HOME/ci/config-system.sh

if dpkg -l xc-usense; then
    echo "XC app xc-usense is installed, reconfigure"
    dpkg-reconfigure xc-usense
fi
